### ISSUE TITLE
rename integration to `philips-airpurifier-coap` to prevent mixups

### ISSUE THREAD

**Issue by betaboon** [betaboon/philips-airpurifier-coap#32]
in order to prevent mixup with other, incompatible integrations i propose renaming this to `philips-airpurifier-coap`.

of course this would be a breaking-change, including the renaming of the integration, the repo and the key in the configuration.

i will not do this right now, but might in a future release.

if anyone is opposing this or has some suggestions or opinions on the issue, this is your chance ;)

refs: #31

**Comment by ronaldt80** [comment]
I already renamed it like that in order to combine with the http variety.
Except for _ instead of - to be consistent.

All for!

**Comment by betaboon** [comment]
merged and released as 0.5.0
i also renamed the repo.
